title: Navigating the Universe
author: benjerminfranklin2020
email: seecompetewin@gmail.com
description: This site will be used to identify and discuss stocks in play in the U.S. equities markets. Focus on options trading, SPACS, Market-Makers, EV and any related subjects

# social links
twitter_username: bisforben2010 # DO NOT include the @ character, or else the build will fail!
github_username:  benjerminfranklin2020 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
style: minima 
